### ISSUE TITLE
Gnome dock/dash border

### ISSUE THREAD

**Issue by in4matix** [imarkoff/Marble-shell-theme#14]
Hello again!

I did some changes to my setup -- using the default Gnome dock/dash, but it has a dark border:
![Screenshot from 2023-12-22 20-02-08](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/bc17fff0-38ce-4ac4-900a-26115c758e06)

And I noticed on your screenshot that no border is present:
![Screenshot from 2023-12-22 20-22-18](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/336c0d34-b97b-4c67-990c-6100f67a65da)

Does your theme control this, and if so, is there a way to remove the border and also to make the opacity darker to match top bar menus?

**Comment by imarkoff** [comment]
Yes, dash with Marble theme has border:
```css
/* Dash */

#dash .dash-background {
        background-color: DASH-COLOR;
        box-shadow: inset 0 0 0 1px BORDER-MENU-SHADOW;
        padding: 4px 2px 4px 2px;
        border-radius: 21px;
}
```
`box-shadow` responds for border color so you can change or remove it in `#dash .dash-background` selector.
