### ISSUE TITLE
Overview thumbnails update

### ISSUE THREAD

**Issue by in4matix** [imarkoff/Marble-shell-theme#28]
Hey,

How you been?

I'm here to nitpick again, sorry!

I installed this extension "Gnome 4x UI Improvements". Is there a way to make the thumbnails less square (rounded corners) ? 

![Screenshot from 2024-06-24 08-26-21](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/b617d8bb-98c4-41b7-8d53-8b1a7322fbce)

**Comment by imarkoff** [comment]
Hi!

`.workspace-thumbnail` responses for thumbnails under the search,
`.workspace-thumbnail-indicator` responses for selected indicator.

```css
.workspace-thumbnail {
	border-radius: 4px;
}

.workspace-thumbnail-indicator {
	border-width: 1px;
	border-radius: 3px;
}
```

But there's one minor defect why this theme still doesn't have rounded thumbnails. Fullscreen windows overflows thumbnails and that's why selected thumbnail may look kinda creepy :(
![image](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/c688dfb2-6071-4b62-97d4-99742b4bb6f4)

However, you can try changing these values. Maybe you'll find the perfect rounding. 🙂
