### ISSUE TITLE
Hello, I am trying to make my own theme base on your project and I need some help

### ISSUE THREAD

**Issue by NeuronSooup** [imarkoff/Marble-shell-theme#7]
First of all, I would like to say this is a great great if not masterpiece of a theme and it is probably a hidden gem. I think you should post this on Unixporn and Gnome subreddit. In gnome 42 there is only 1 theme I find amazing which looks exactly like Marble shell but made by a different person, he is sadly no longer active on any socials. Therefore, I created my own theme based on that which were great until gnome 44
Check them out: https://www.reddit.com/r/unixporn/comments/10a4svm/gnome_do_i_wanna_know/ and https://www.reddit.com/r/unixporn/comments/zkx0qo/gnome_where_is_my_mind_its_cozy_christmas_time/

Now with gnome 44 the pill shaped settings are a bit bigger which ruin every gnome 43 theme which looks similar to mine. Luckily, I have found your project. There are a few theme which looks similar to yours, like the Mono-gtk-theme  but they look a bit worse to me because of some small elements like roundness 

Anyways, I am trying to make a new color scheme based on your theme which looks exactly like this https://www.reddit.com/r/unixporn/comments/10a4svm/gnome_do_i_wanna_know/

So far so good but I have some trouble with these 2 element which is described here https://imgur.com/a/oJMyW6V

Can you help me out? Thank you for this amazing shell theme

**Comment by imarkoff** [comment]
Thank you very much for your sincere assessment. It is extremely motivating and pleasant to hear such words.💓

> So far so good but I have some trouble with these 2 element which is described here.

You can modify quick settings background color and button color in auth dialog using this style:
```css
.quick-settings {
	background-color: rgb(25, 23, 36);
}

.modal-dialog-linked-button:last-child {
	background-color: rgb(196, 167, 231) ;
}

.modal-dialog-linked-button:last-child:hover,
.modal-dialog-linked-button:last-child:focus {
	background-color: rgba(196, 167, 231, 0.8) ;
}

.modal-dialog .modal-dialog-linked-button:insensitive,
.hotplug-notification-item:insensitive,
.notification-banner .notification-button:insensitive {
	background-color: rgba(196, 167, 231, 0.6);
}
``` 

But there is one small problem with this theme: all colors are generated automatically, and editing the generated file is a bit of a pain. However, if you don't intend to create more theme color variants, you can modify the generated file as well. 

If you have any troubles, I'm happy to help you with them.
